# Generated by Django 5.0 on 2024-03-19 15:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=100)),
                ('line2', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('created_by', models.IntegerField()),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobno', models.BigIntegerField()),
                ('emailid', models.EmailField(max_length=400, null=True)),
                ('accountno', models.IntegerField()),
                ('beneficiaryname', models.CharField(max_length=300)),
                ('created_by', models.IntegerField()),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=300)),
                ('lastname', models.CharField(max_length=200)),
                ('userid', models.CharField(max_length=200)),
                ('password', models.IntegerField()),
                ('mblenum', models.BigIntegerField()),
                ('email', models.EmailField(max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorDtails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
                ('gst', models.CharField(max_length=200)),
                ('pan', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=300)),
                ('created_by', models.IntegerField()),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_date', models.DateField(blank=True, null=True)),
                ('AddressDetails', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_details.addressdetails')),
                ('ContactDetails', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_details.contactdetails')),
            ],
        ),
    ]
