# Generated by Django 5.0 on 2024-03-21 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendordtails',
            old_name='AddressDetails',
            new_name='Address_Details',
        ),
        migrations.RenameField(
            model_name='vendordtails',
            old_name='ContactDetails',
            new_name='Contact_Details',
        ),
    ]
